// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/case-studies/VariantA.tsx": () => import("../components/mockups/case-studies/VariantA.tsx"),
  "./components/mockups/case-studies/VariantB.tsx": () => import("../components/mockups/case-studies/VariantB.tsx"),
  "./components/mockups/case-studies/VariantC.tsx": () => import("../components/mockups/case-studies/VariantC.tsx"),
  "./components/mockups/portfolio-variations/BoldModular.tsx": () => import("../components/mockups/portfolio-variations/BoldModular.tsx"),
  "./components/mockups/portfolio-variations/Conversation.tsx": () => import("../components/mockups/portfolio-variations/Conversation.tsx"),
  "./components/mockups/portfolio-variations/DeepDiveFirst.tsx": () => import("../components/mockups/portfolio-variations/DeepDiveFirst.tsx"),
  "./components/mockups/portfolio-variations/EditorialLayout1.tsx": () => import("../components/mockups/portfolio-variations/EditorialLayout1.tsx"),
  "./components/mockups/portfolio-variations/EditorialLayout2.tsx": () => import("../components/mockups/portfolio-variations/EditorialLayout2.tsx"),
  "./components/mockups/portfolio-variations/EditorialLayout3.tsx": () => import("../components/mockups/portfolio-variations/EditorialLayout3.tsx"),
  "./components/mockups/portfolio-variations/IndexGallery.tsx": () => import("../components/mockups/portfolio-variations/IndexGallery.tsx"),
  "./components/mockups/portfolio-variations/MinimalistSingular.tsx": () => import("../components/mockups/portfolio-variations/MinimalistSingular.tsx"),
  "./components/mockups/portfolio-variations/TimelineJourney.tsx": () => import("../components/mockups/portfolio-variations/TimelineJourney.tsx")
};
